### ISSUE TITLE
Feature request: make the sender name configurable

### ISSUE THREAD

**Issue by stevejalim** [yunojuno/hipchat-notifications#1]
Looking over the code, I can't see where is best to plug in a varying 'sender' string/label. 

It would be good if a specific label for the sender could be set, either via explicit arg or from an env var - whatever feels best - so that if two things are pushing data into the same Hipchat, we can use the label as a quick indication of the source

**Comment by hugorodgerbrown** [comment]
It's the 'label' param on the `notify_room` function, which can also be
passed in to the colour functions. It gets appended to the sender name,
which is taken from the auth_token owner. ("A label to be shown in addition
to the sender's name.")

**Comment by stevejalim** [comment]
Thanks for the clarification!
